
package com.xiejinhua.example.main;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService1Soap", targetNamespace = "http://tempuri.org/")
public interface WebService1Soap {


    /**
     * 采购入库单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_Rdrecord01Save", action = "http://tempuri.org/U8_Rdrecord01Save")
    @WebResult(name = "U8_Rdrecord01SaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_Rdrecord01Save", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord01Save")
    @ResponseWrapper(localName = "U8_Rdrecord01SaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord01SaveResponse")
    public String u8Rdrecord01Save(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 调拨单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_TransVouchSave", action = "http://tempuri.org/U8_TransVouchSave")
    @WebResult(name = "U8_TransVouchSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_TransVouchSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8TransVouchSave")
    @ResponseWrapper(localName = "U8_TransVouchSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8TransVouchSaveResponse")
    public String u8TransVouchSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 销售发货单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_DispatchBlueSave", action = "http://tempuri.org/U8_DispatchBlueSave")
    @WebResult(name = "U8_DispatchBlueSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_DispatchBlueSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8DispatchBlueSave")
    @ResponseWrapper(localName = "U8_DispatchBlueSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8DispatchBlueSaveResponse")
    public String u8DispatchBlueSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 销售发票
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_SalebillVouchSave", action = "http://tempuri.org/U8_SalebillVouchSave")
    @WebResult(name = "U8_SalebillVouchSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_SalebillVouchSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8SalebillVouchSave")
    @ResponseWrapper(localName = "U8_SalebillVouchSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8SalebillVouchSaveResponse")
    public String u8SalebillVouchSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 其他入库单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_Rdrecord08Save", action = "http://tempuri.org/U8_Rdrecord08Save")
    @WebResult(name = "U8_Rdrecord08SaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_Rdrecord08Save", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord08Save")
    @ResponseWrapper(localName = "U8_Rdrecord08SaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord08SaveResponse")
    public String u8Rdrecord08Save(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 其他出库单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_Rdrecord09Save", action = "http://tempuri.org/U8_Rdrecord09Save")
    @WebResult(name = "U8_Rdrecord09SaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_Rdrecord09Save", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord09Save")
    @ResponseWrapper(localName = "U8_Rdrecord09SaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8Rdrecord09SaveResponse")
    public String u8Rdrecord09Save(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 收款单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_GatheringSave", action = "http://tempuri.org/U8_GatheringSave")
    @WebResult(name = "U8_GatheringSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_GatheringSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8GatheringSave")
    @ResponseWrapper(localName = "U8_GatheringSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8GatheringSaveResponse")
    public String u8GatheringSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 付款单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_PaymentSave", action = "http://tempuri.org/U8_PaymentSave")
    @WebResult(name = "U8_PaymentSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_PaymentSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8PaymentSave")
    @ResponseWrapper(localName = "U8_PaymentSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8PaymentSaveResponse")
    public String u8PaymentSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 销售订单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_SoMainSave", action = "http://tempuri.org/U8_SoMainSave")
    @WebResult(name = "U8_SoMainSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_SoMainSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8SoMainSave")
    @ResponseWrapper(localName = "U8_SoMainSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8SoMainSaveResponse")
    public String u8SoMainSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 存货档案
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_InventorySave", action = "http://tempuri.org/U8_InventorySave")
    @WebResult(name = "U8_InventorySaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_InventorySave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8InventorySave")
    @ResponseWrapper(localName = "U8_InventorySaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8InventorySaveResponse")
    public String u8InventorySave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 客户档案
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_CustomerSave", action = "http://tempuri.org/U8_CustomerSave")
    @WebResult(name = "U8_CustomerSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_CustomerSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8CustomerSave")
    @ResponseWrapper(localName = "U8_CustomerSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8CustomerSaveResponse")
    public String u8CustomerSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 供应商档案
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_VendorSave", action = "http://tempuri.org/U8_VendorSave")
    @WebResult(name = "U8_VendorSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_VendorSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8VendorSave")
    @ResponseWrapper(localName = "U8_VendorSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8VendorSaveResponse")
    public String u8VendorSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

    /**
     * 其他应付单
     * 
     * @param jSon
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "U8_APVouchSave", action = "http://tempuri.org/U8_APVouchSave")
    @WebResult(name = "U8_APVouchSaveResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "U8_APVouchSave", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8APVouchSave")
    @ResponseWrapper(localName = "U8_APVouchSaveResponse", targetNamespace = "http://tempuri.org/", className = "dcms.ebridge.u8.bo.U8APVouchSaveResponse")
    public String u8APVouchSave(
        @WebParam(name = "JSon", targetNamespace = "http://tempuri.org/")
        String jSon);

}
